import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
ev_data = pd.read_csv("A:\\Data Science\\us_car_data.csv")
print(ev_data.isnull().sum())
print(ev_data.describe())
plt.figure(figsize=(12, 6))
ev_data['Make'].value_counts().plot(kind='bar')
plt.title('Count of Vehicles by Make')
plt.xticks(rotation=90)
plt.xlabel('Make')
plt.ylabel('Count')
plt.show()
plt.figure(figsize=(10, 6))
ev_data['Model Year'].value_counts().sort_index().plot(kind='bar')
plt.title('Count of Vehicles by Model Year')
plt.xlabel('Model Year')
plt.ylabel('Count')
plt.show()
correlation_matrix = ev_data.corr()
plt.figure(figsize=(10, 8))
plt.imshow(correlation_matrix, cmap='coolwarm', aspect='auto')
plt.title('Correlation Matrix')
plt.colorbar()
plt.xticks(np.arange(len(correlation_matrix.columns)), correlation_matrix.columns, rotation=45)
plt.yticks(np.arange(len(correlation_matrix.columns)), correlation_matrix.columns)
plt.show()
